[build] command = "npm run build" publish = "dist" functions = "netlify/functions"

[[redirects]] from = "/*" to = "/index.html" status = 200

[[headers]] for = "/*" [headers.values] Referrer-Policy = "strict-origin-when-cross-origin" X-Frame-Options = "SAMEORIGIN" X-Content-Type-Options = "nosniff"